import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename } from "node:path";
import * as sass from "sass";

const versionPattern = /^\$css-version:\s*"([^"]*)";\n/m;
// Magic CSS bundles an old Sass that rejects space-separated colors like rgb(0 0 0 / 0.1).
const modernColor = /\b(rgba?|hsla?)\(\s*[^,()]*?\d[^,()]*\s+[\d.]+%?\s+[\d.]+%?(\s*\/[^)]*)?\)/;
const literalColor = /#[0-9a-fA-F]{3,8}\b|\b(rgba?|hsla?)\(/;

const errors = [];
const stripComment = (line) => line.replace(/(^|\s)\/\/.*$/, "");

function lint(file, text, { variablesOnly = false } = {}) {
  text.split("\n").forEach((line, i) => {
    const code = stripComment(line);
    if (modernColor.test(code)) {
      errors.push(`${file}:${i + 1}: use comma-separated colors for Magic CSS, e.g. rgba(0, 0, 0, 0.1)\n    ${line.trim()}`);
    } else if (variablesOnly && literalColor.test(code.replace(/'[^']*'|"[^"]*"/g, ""))) {
      errors.push(`${file}:${i + 1}: rules.scss should use theme variables, not literal colors\n    ${line.trim()}`);
    }
  });
}

const rules = readFileSync("rules.scss", "utf8");
const version = rules.match(versionPattern);
if (!version) {
  errors.push("rules.scss: missing $css-version declaration");
}
lint("rules.scss", rules, { variablesOnly: true });

const themes = readdirSync("themes").filter((f) => f.endsWith(".scss")).sort();
if (!themes.length) errors.push("themes/: no theme files found");

rmSync("dist", { recursive: true, force: true });
mkdirSync("dist");

for (const file of themes) {
  const name = basename(file, ".scss");
  const theme = readFileSync(`themes/${file}`, "utf8");
  lint(`themes/${file}`, theme);
  if (!version) continue;

  const out = [
    `// GENERATED by npm run build from themes/${file} + rules.scss. Do not edit;`,
    "// paste this whole file into Magic CSS (SCSS mode).",
    version[0],
    theme.trimEnd(),
    "",
    rules.replace(versionPattern, "").trimEnd(),
    "",
  ].join("\n");
  writeFileSync(`dist/${name}.scss`, out);

  try {
    sass.compileString(out, { syntax: "scss" });
    console.log(`dist/${name}.scss: OK (CSS ${version[1]})`);
  } catch (err) {
    errors.push(`dist/${name}.scss: does not compile\n${err.message}`);
  }
}

if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}
